### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'Tensor'

### ISSUE THREAD

**Issue by mariaWitch** [ashen-sensored/sd_webui_SAG#11]
Currently receiving this error on Img2Img. Not sure what is causing it per se, but this was used in conjunction with Multi-diffusion's noise inversion, and Dynamic CFG when the error occured.
```python
Error executing callback cfg_after_cfg_callback for /home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/script_callbacks.py", line 201, in cfg_after_cfg_callback
    c.callback(params)
  File "/home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py", line 242, in cfg_after_cfg_callback
    params.x = params.x + (current_uncond_pred - (current_degraded_pred + current_degraded_pred_compensation)) * float(current_sag_guidance_scale)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'Tensor'
```

**Comment by mariaWitch** [comment]
Actually this seems to be a combination of different errors?
This might be hard to track down. Here are the other two I encountered. (I was able to trace it to Noise Inversion from Multi-Diffusion)

```python
Error executing callback cfg_denoised_callback for /home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/script_callbacks.py", line 193, in cfg_denoised_callback
    c.callback(params)
  File "/home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py", line 214, in denoised_callback
    attn_mask.reshape(b, middle_layer_latent_size[0], middle_layer_latent_size[1])
RuntimeError: shape '[1, 16, 20]' is invalid for input of size 144

Error executing callback cfg_after_cfg_callback for /home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py
Traceback (most recent call last):
  File "/home/maria/stable-diffusion-webui/modules/script_callbacks.py", line 201, in cfg_after_cfg_callback
    c.callback(params)
  File "/home/maria/stable-diffusion-webui/extensions/sd_webui_SAG/scripts/SAG.py", line 242, in cfg_after_cfg_callback
    params.x = params.x + (current_uncond_pred - (current_degraded_pred + current_degraded_pred_compensation)) * float(current_sag_guidance_scale)
RuntimeError: The size of tensor a (160) must match the size of tensor b (80) at non-singleton dimension 3
```

**Comment by Razunter** [comment]
~~Just started to get this error in txt2img with [Vladmandic's fork](https://github.com/vladmandic/automatic/)~~
Getting this error with inpainting model selected.

**Comment by Elevory** [comment]
I'm also getting this error with inpainting models.
