### ISSUE TITLE
Broken after new AUTO1111 update.

### ISSUE THREAD

**Issue by enternalsaga** [ashen-sensored/sd_webui_SAG#12]
Hello, 
Since the new update from AUTO the extension stops working. Issue state:

File "I:\stable-diffusion-webui\modules\[scripts.py](https://scripts.py/)", line 256, in load_scripts

script_module = script_loading.load_module(scriptfile.path)

File "I:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module

module_spec.loader.exec_module(module)

File "<frozen importlib._bootstrap_external>", line 883, in exec_module

File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

File "I:\stable-diffusion-webui\extensions\sd_webui_SAG\scripts\[SAG.py](https://sag.py/)", line 18, in <module>

from modules.script_callbacks import on_cfg_denoiser,CFGDenoiserParams, CFGDenoisedParams, on_cfg_denoised, AfterCFGCallbackParams, on_cfg_after_cfg

ImportError: cannot import name 'AfterCFGCallbackParams' from 'modules.script_callbacks' (I:\stable-diffusion-webui\modules\script_callbacks.py)

Hope you can fix it soon. Thank you.

**Comment by enternalsaga** [comment]
FYI. Your stealth_pnginfo also broken due to new update.

**Comment by Squibeel** [comment]
Can confirm it stops working because script_callback.py and sd_samplers_kdiffusion.py need to be patched again.
After manually patching it because the patcher didn't work I managed to get it working.

Here's the two patched files just in case people don't want to wait for the update.
https://easyupload.io/dgsodf

**Comment by CamWiseOwl** [comment]
That link didn't work for me so I've created my own patch here on GitHub's gists - https://gist.github.com/CamWiseOwl/eb13ba59e8750717f20db3af7f8364db

Looks like it's only sd_samplers_kdiffusion.py that needed updating for the latest update.

**Comment by ghost** [comment]
> That link didn't work for me so I've created my own patch here on GitHub's gists - https://gist.github.com/CamWiseOwl/eb13ba59e8750717f20db3af7f8364db
> 
> Looks like it's only sd_samplers_kdiffusion.py that needed updating for the latest update.

Would you mind explaining briefly how I can apply this script? I don't mind looking up the finer details, I just need to understand where this script is applied. Thanks.

**Comment by Squibeel** [comment]
Strange, it works for me...
Here goes mediafire then - https://www.mediafire.com/file/ozddr7248gmecr0/patched.zip/file

**Comment by CamWiseOwl** [comment]
> > That link didn't work for me so I've created my own patch here on GitHub's gists - https://gist.github.com/CamWiseOwl/eb13ba59e8750717f20db3af7f8364db
> > Looks like it's only sd_samplers_kdiffusion.py that needed updating for the latest update.
> 
> Would you mind explaining briefly how I can apply this script? I don't mind looking up the finer details, I just need to understand where this script is applied. Thanks.


Either download @Squibeel's zip and directly replace the files or save my gist somewhere then run git apply in the root A1111 folder like the readme describes how to do -
`git apply --ignore-whitespace path/to/updated.patch`

**Comment by enternalsaga** [comment]
> Strange, it works for me... Here goes mediafire then - https://www.mediafire.com/file/ozddr7248gmecr0/patched.zip/file

Thank you but still did not work. 
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "I:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\stable-diffusion-webui\extensions\04.sd_webui_SAG\scripts\SAG.py", line 18, in <module>
    from modules.script_callbacks import on_cfg_denoiser,CFGDenoiserParams, CFGDenoisedParams, on_cfg_denoised, AfterCFGCallbackParams, on_cfg_after_cfg
ImportError: cannot import name 'AfterCFGCallbackParams' from 'modules.script_callbacks' (I:\stable-diffusion-webui\modules\script_callbacks.py)
