### ISSUE TITLE
conflict with sd_grid_add_image_number

### ISSUE THREAD

**Issue by sdbds** [ashen-sensored/sd_webui_SAG#5]
XYZ↓

Error executing callback image_saved_callback for H:\novelai-webui-aki-v2\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py
Traceback (most recent call last):
  File "H:\novelai-webui-aki-v2\modules\script_callbacks.py", line 177, in image_saved_callback
    c.callback(params)
  File "H:\novelai-webui-aki-v2\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py", line 67, in handle_image_saved
    getaxis_value(params.p, img_filename, "xyz_plot_x")
  File "H:\novelai-webui-aki-v2\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py", line 50, in getaxis_value
    axis_option = xyz_options[getattr(getattr(state, getaxis), "axis").label]
KeyError: 'SAG Guidance Scale'

one img↓

Error executing callback image_saved_callback for H:\novelai-webui-aki-v2\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py
Traceback (most recent call last):
  File "H:\novelai-webui-aki-v2\modules\script_callbacks.py", line 177, in image_saved_callback
    c.callback(params)
  File "H:\novelai-webui-aki-v2\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py", line 67, in handle_image_saved
    getaxis_value(params.p, img_filename, "xyz_plot_x")
  File "H:\novelai-webui-aki-v2\extensions\sd_grid_add_image_number\scripts\sd_grid_add_image_number.py", line 50, in getaxis_value
    axis_option = xyz_options[getattr(getattr(state, getaxis), "axis").label]
KeyError: 'SAG Guidance Scale'

**Comment by sdbds** [comment]
I think this mistake may be related to grid imgs, even if generating a picture will also generate additional grid imgs.
